// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodeUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using DevExpress.CodedUIExtension.DXTestControls.v20_1;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod_TestTimSanPham - Use 'RecordedMethod_TestTimSanPhamParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_TestTimSanPham()
        {
            #region Variable Declarations
            WinComboBox uICboxTimKiemComboBox = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UICboxTimKiemWindow.UICboxTimKiemComboBox;
            WinEdit uITbTimKiemEdit = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UITbTimKiemWindow.UITbTimKiemEdit;
            WinEdit uITbTimKiemEdit1 = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UITbTimKiemWindow.UITbTimKiemEdit1;
            WinButton uITìmKiếmButton = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UITìmKiếmWindow.UITìmKiếmButton;
            #endregion

            // Select 'Tìm Theo Mã' in 'cboxTimKiem' combo box
            uICboxTimKiemComboBox.SelectedItem = this.RecordedMethod_TestTimSanPhamParams.UICboxTimKiemComboBoxSelectedItem;

            // Click 'tbTimKiem' text box
            Mouse.Click(uITbTimKiemEdit, new Point(52, 9));

            // Type 'sp000000000000000001' in 'tbTimKiem' text box
            uITbTimKiemEdit1.Text = this.RecordedMethod_TestTimSanPhamParams.UITbTimKiemEdit1Text;

            // Click 'Tìm Kiếm' button
            Mouse.Click(uITìmKiếmButton, new Point(54, 15));
        }
        
        /// <summary>
        /// AssertMethod_SoSanhUC - Use 'AssertMethod_SoSanhUCExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_SoSanhUC()
        {
            #region Variable Declarations
            WinClient uIUCSanPhamClient = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIUCSanPhamWindow.UIUCSanPhamClient;
            #endregion

            // Verify that the 'ControlType' property of 'UCSanPham' client equals 'Client'
            Assert.AreEqual(this.AssertMethod_SoSanhUCExpectedValues.UIUCSanPhamClientControlType, uIUCSanPhamClient.ControlType.ToString());
        }
        
        /// <summary>
        /// AssertMethod_SoSanhPnAnhSanPhamBoSung - Use 'AssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_SoSanhPnAnhSanPhamBoSung()
        {
            #region Variable Declarations
            WinClient uIPnAnhSanPhamClient = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIPnAnhSanPhamWindow.UIPnAnhSanPhamClient;
            #endregion

            // Verify that the 'ControlType' property of 'pnAnhSanPham' client equals 'Client'
            Assert.AreEqual(this.AssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues.UIPnAnhSanPhamClientControlType, uIPnAnhSanPhamClient.ControlType.ToString());
        }
        
        /// <summary>
        /// AssertMethod_SoSanhSoLuongSanPhamTimBoSung - Use 'AssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_SoSanhSoLuongSanPhamTimBoSung()
        {
            #region Variable Declarations
            WinClient uIPnSanPhamsClient = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIPnSanPhamsWindow.UIPnSanPhamsClient;
            #endregion

            // Verify that the 'ControlType' property of 'pnSanPhams' client equals 'Client'
            Assert.AreEqual(this.AssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues.UIPnSanPhamsClientControlType, uIPnSanPhamsClient.ControlType.ToString());
        }
        
        /// <summary>
        /// RecordedMethod_TestTimSanPhamTheoTen - Use 'RecordedMethod_TestTimSanPhamTheoTenParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_TestTimSanPhamTheoTen()
        {
            #region Variable Declarations
            WinComboBox uICboxTimKiemComboBox = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UICboxTimKiemWindow.UICboxTimKiemComboBox;
            WinRadioButton uITrên5TriệuRadioButton = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UITrên5TriệuWindow.UITrên5TriệuRadioButton;
            WinRadioButton uIDưới5TriệuTrên2TriệuRadioButton = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIDưới5TriệuTrên2TriệuWindow.UIDưới5TriệuTrên2TriệuRadioButton;
            WinRadioButton uIDưới2TriệuRadioButton = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIDưới2TriệuWindow.UIDưới2TriệuRadioButton;
            WinCheckBox uIGiáTiềnCheckBox = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIGiáTiềnWindow.UIGiáTiềnCheckBox;
            WinEdit uITbTimKiemEdit = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UITbTimKiemWindow.UITbTimKiemEdit;
            WinEdit uITbTimKiemEdit1 = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UITbTimKiemWindow.UITbTimKiemEdit1;
            WinButton uITìmKiếmButton = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UITìmKiếmWindow.UITìmKiếmButton;
            #endregion

            // Select 'Tìm Theo Tên' in 'cboxTimKiem' combo box
            uICboxTimKiemComboBox.SelectedItem = this.RecordedMethod_TestTimSanPhamTheoTenParams.UICboxTimKiemComboBoxSelectedItem;

            // Select 'Trên 5 Triệu' radio button
            uITrên5TriệuRadioButton.Selected = this.RecordedMethod_TestTimSanPhamTheoTenParams.UITrên5TriệuRadioButtonSelected;

            // Select 'Dưới 5 Triệu Trên 2 Triệu' radio button
            uIDưới5TriệuTrên2TriệuRadioButton.Selected = this.RecordedMethod_TestTimSanPhamTheoTenParams.UIDưới5TriệuTrên2TriệuRadioButtonSelected;

            // Select 'Dưới 2 Triệu' radio button
            uIDưới2TriệuRadioButton.Selected = this.RecordedMethod_TestTimSanPhamTheoTenParams.UIDưới2TriệuRadioButtonSelected;

            // Select '+ Giá Tiền' check box
            uIGiáTiềnCheckBox.Checked = this.RecordedMethod_TestTimSanPhamTheoTenParams.UIGiáTiềnCheckBoxChecked;

            // Move 'tbTimKiem' text box to 'Dưới 5 Triệu Trên 2 Triệu' radio button
            uIDưới5TriệuTrên2TriệuRadioButton.EnsureClickable(new Point(79, 19));
            Mouse.StartDragging(uITbTimKiemEdit, new Point(41, 11));
            Mouse.StopDragging(uIDưới5TriệuTrên2TriệuRadioButton, new Point(79, 19));

            // Type 'iphone' in 'tbTimKiem' text box
            uITbTimKiemEdit1.Text = this.RecordedMethod_TestTimSanPhamTheoTenParams.UITbTimKiemEdit1Text;

            // Click 'Tìm Kiếm' button
            Mouse.Click(uITìmKiếmButton, new Point(60, 26));
        }
        
        /// <summary>
        /// RecordedMethod_TestTangSoLuongMua
        /// </summary>
        public void RecordedMethod_TestTangSoLuongMua()
        {
            #region Variable Declarations
            WinText uIItemText = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIUCSanPhamWindow.UIItemText;
            #endregion

            // Click '+' label
            Mouse.Click(uIItemText, new Point(12, 16));
        }
        
        /// <summary>
        /// AssertMethod_TestTangSoLuong - Use 'AssertMethod_TestTangSoLuongExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_TestTangSoLuong()
        {
            #region Variable Declarations
            WinClient uIUCSanPhamClient = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIUCSanPhamWindow.UIUCSanPhamClient;
            WinEdit uITxtTongTienEdit = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIItem24000000Window.UITxtTongTienEdit;
            WinEdit uITxtTongSoLuongEdit = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIItem1CáiWindow.UITxtTongSoLuongEdit;
            #endregion

            // Verify that the 'ControlType' property of 'UCSanPham' client equals 'Client'
            Assert.AreEqual(this.AssertMethod_TestTangSoLuongExpectedValues.UIUCSanPhamClientControlType, uIUCSanPhamClient.ControlType.ToString());

            // Verify that the 'Text' property of 'txtTongTien' text box equals '48,000,000'
            Assert.AreEqual(this.AssertMethod_TestTangSoLuongExpectedValues.UITxtTongTienEditText, uITxtTongTienEdit.Text);

            // Verify that the 'Text' property of 'txtTongSoLuong' text box equals '2 Cái'
            Assert.AreEqual(this.AssertMethod_TestTangSoLuongExpectedValues.UITxtTongSoLuongEditText, uITxtTongSoLuongEdit.Text);
        }
        
        /// <summary>
        /// RecordedMethod_TestGiamSoLuongMua
        /// </summary>
        public void RecordedMethod_TestGiamSoLuongMua()
        {
            #region Variable Declarations
            WinText uIItemText1 = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIUCSanPhamWindow.UIItemText1;
            #endregion

            // Click '-' label
            Mouse.Click(uIItemText1, new Point(16, 17));
        }
        
        /// <summary>
        /// RecordedMethod_Init_TestGiamSoLuongMua
        /// </summary>
        public void RecordedMethod_Init_TestGiamSoLuongMua()
        {
            #region Variable Declarations
            WinClient uIPnAnhSanPhamClient = this.UIFrmQuanLyWindow.UIMdiClientTabList.UIFrmBanHangWindow.UIFrmBanHangWindow1.UIPnAnhSanPhamWindow.UIPnAnhSanPhamClient;
            WinButton uIXácNhậnButton = this.UIFrmChonKhachHangWindow.UIXácNhậnWindow.UIXácNhậnButton;
            WinControl uIThôngBáoDialog = this.UIThôngBáoWindow.UIThôngBáoDialog;
            WinButton uIOKButton = this.UIThôngBáoWindow.UIOKWindow.UIOKButton;
            #endregion

            // Click 'pnAnhSanPham' client
            Mouse.Click(uIPnAnhSanPhamClient, new Point(62, 59));

            // Click 'Xác Nhận' button
            Mouse.Click(uIXácNhậnButton, new Point(40, 9));

            // Click 'Thông Báo' Dialog
            Mouse.Click(uIThôngBáoDialog, new Point(291, 101));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(58, 11));
        }
        
        #region Properties
        public virtual RecordedMethod_TestTimSanPhamParams RecordedMethod_TestTimSanPhamParams
        {
            get
            {
                if ((this.mRecordedMethod_TestTimSanPhamParams == null))
                {
                    this.mRecordedMethod_TestTimSanPhamParams = new RecordedMethod_TestTimSanPhamParams();
                }
                return this.mRecordedMethod_TestTimSanPhamParams;
            }
        }
        
        public virtual AssertMethod_SoSanhUCExpectedValues AssertMethod_SoSanhUCExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_SoSanhUCExpectedValues == null))
                {
                    this.mAssertMethod_SoSanhUCExpectedValues = new AssertMethod_SoSanhUCExpectedValues();
                }
                return this.mAssertMethod_SoSanhUCExpectedValues;
            }
        }
        
        public virtual AssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues AssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues == null))
                {
                    this.mAssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues = new AssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues();
                }
                return this.mAssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues;
            }
        }
        
        public virtual AssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues AssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues == null))
                {
                    this.mAssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues = new AssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues();
                }
                return this.mAssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues;
            }
        }
        
        public virtual RecordedMethod_TestTimSanPhamTheoTenParams RecordedMethod_TestTimSanPhamTheoTenParams
        {
            get
            {
                if ((this.mRecordedMethod_TestTimSanPhamTheoTenParams == null))
                {
                    this.mRecordedMethod_TestTimSanPhamTheoTenParams = new RecordedMethod_TestTimSanPhamTheoTenParams();
                }
                return this.mRecordedMethod_TestTimSanPhamTheoTenParams;
            }
        }
        
        public virtual AssertMethod_TestTangSoLuongExpectedValues AssertMethod_TestTangSoLuongExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_TestTangSoLuongExpectedValues == null))
                {
                    this.mAssertMethod_TestTangSoLuongExpectedValues = new AssertMethod_TestTangSoLuongExpectedValues();
                }
                return this.mAssertMethod_TestTangSoLuongExpectedValues;
            }
        }
        
        public UIFrmQuanLyWindow UIFrmQuanLyWindow
        {
            get
            {
                if ((this.mUIFrmQuanLyWindow == null))
                {
                    this.mUIFrmQuanLyWindow = new UIFrmQuanLyWindow();
                }
                return this.mUIFrmQuanLyWindow;
            }
        }
        
        public UIFrmChonKhachHangWindow UIFrmChonKhachHangWindow
        {
            get
            {
                if ((this.mUIFrmChonKhachHangWindow == null))
                {
                    this.mUIFrmChonKhachHangWindow = new UIFrmChonKhachHangWindow();
                }
                return this.mUIFrmChonKhachHangWindow;
            }
        }
        
        public UIThôngBáoWindow UIThôngBáoWindow
        {
            get
            {
                if ((this.mUIThôngBáoWindow == null))
                {
                    this.mUIThôngBáoWindow = new UIThôngBáoWindow();
                }
                return this.mUIThôngBáoWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod_TestTimSanPhamParams mRecordedMethod_TestTimSanPhamParams;
        
        private AssertMethod_SoSanhUCExpectedValues mAssertMethod_SoSanhUCExpectedValues;
        
        private AssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues mAssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues;
        
        private AssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues mAssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues;
        
        private RecordedMethod_TestTimSanPhamTheoTenParams mRecordedMethod_TestTimSanPhamTheoTenParams;
        
        private AssertMethod_TestTangSoLuongExpectedValues mAssertMethod_TestTangSoLuongExpectedValues;
        
        private UIFrmQuanLyWindow mUIFrmQuanLyWindow;
        
        private UIFrmChonKhachHangWindow mUIFrmChonKhachHangWindow;
        
        private UIThôngBáoWindow mUIThôngBáoWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_TestTimSanPham'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RecordedMethod_TestTimSanPhamParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Tìm Theo Mã' in 'cboxTimKiem' combo box
        /// </summary>
        public string UICboxTimKiemComboBoxSelectedItem = "Tìm Theo Mã";
        
        /// <summary>
        /// Type 'sp000000000000000001' in 'tbTimKiem' text box
        /// </summary>
        public string UITbTimKiemEdit1Text = "sp000000000000000001";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_SoSanhUC'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AssertMethod_SoSanhUCExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'UCSanPham' client equals 'Client'
        /// </summary>
        public string UIUCSanPhamClientControlType = "Client";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_SoSanhPnAnhSanPhamBoSung'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AssertMethod_SoSanhPnAnhSanPhamBoSungExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'pnAnhSanPham' client equals 'Client'
        /// </summary>
        public string UIPnAnhSanPhamClientControlType = "Client";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_SoSanhSoLuongSanPhamTimBoSung'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AssertMethod_SoSanhSoLuongSanPhamTimBoSungExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'pnSanPhams' client equals 'Client'
        /// </summary>
        public string UIPnSanPhamsClientControlType = "Client";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_TestTimSanPhamTheoTen'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RecordedMethod_TestTimSanPhamTheoTenParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Tìm Theo Tên' in 'cboxTimKiem' combo box
        /// </summary>
        public string UICboxTimKiemComboBoxSelectedItem = "Tìm Theo Tên";
        
        /// <summary>
        /// Select 'Trên 5 Triệu' radio button
        /// </summary>
        public bool UITrên5TriệuRadioButtonSelected = true;
        
        /// <summary>
        /// Select 'Dưới 5 Triệu Trên 2 Triệu' radio button
        /// </summary>
        public bool UIDưới5TriệuTrên2TriệuRadioButtonSelected = true;
        
        /// <summary>
        /// Select 'Dưới 2 Triệu' radio button
        /// </summary>
        public bool UIDưới2TriệuRadioButtonSelected = true;
        
        /// <summary>
        /// Select '+ Giá Tiền' check box
        /// </summary>
        public bool UIGiáTiềnCheckBoxChecked = true;
        
        /// <summary>
        /// Type 'iphone' in 'tbTimKiem' text box
        /// </summary>
        public string UITbTimKiemEdit1Text = "iphone";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_TestTangSoLuong'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AssertMethod_TestTangSoLuongExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'UCSanPham' client equals 'Client'
        /// </summary>
        public string UIUCSanPhamClientControlType = "Client";
        
        /// <summary>
        /// Verify that the 'Text' property of 'txtTongTien' text box equals '48,000,000'
        /// </summary>
        public string UITxtTongTienEditText = "48,000,000";
        
        /// <summary>
        /// Verify that the 'Text' property of 'txtTongSoLuong' text box equals '2 Cái'
        /// </summary>
        public string UITxtTongSoLuongEditText = "2 Cái";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFrmQuanLyWindow : WinWindow
    {
        
        public UIFrmQuanLyWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "frmQuanLy";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public UIMdiClientTabList UIMdiClientTabList
        {
            get
            {
                if ((this.mUIMdiClientTabList == null))
                {
                    this.mUIMdiClientTabList = new UIMdiClientTabList(this);
                }
                return this.mUIMdiClientTabList;
            }
        }
        #endregion
        
        #region Fields
        private UIMdiClientTabList mUIMdiClientTabList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMdiClientTabList : DXTestControl
    {
        
        public UIMdiClientTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "MdiClient[0]";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "MdiClient";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public UIFrmBanHangWindow UIFrmBanHangWindow
        {
            get
            {
                if ((this.mUIFrmBanHangWindow == null))
                {
                    this.mUIFrmBanHangWindow = new UIFrmBanHangWindow(this);
                }
                return this.mUIFrmBanHangWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFrmBanHangWindow mUIFrmBanHangWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFrmBanHangWindow : DXWindow
    {
        
        public UIFrmBanHangWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "frmBanHang";
            this.SearchProperties.Add(new PropertyExpression(DXTestControl.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public UIFrmBanHangWindow1 UIFrmBanHangWindow1
        {
            get
            {
                if ((this.mUIFrmBanHangWindow1 == null))
                {
                    this.mUIFrmBanHangWindow1 = new UIFrmBanHangWindow1(this);
                }
                return this.mUIFrmBanHangWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIFrmBanHangWindow1 mUIFrmBanHangWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFrmBanHangWindow1 : WinWindow
    {
        
        public UIFrmBanHangWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "frmBanHang";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public UICboxTimKiemWindow UICboxTimKiemWindow
        {
            get
            {
                if ((this.mUICboxTimKiemWindow == null))
                {
                    this.mUICboxTimKiemWindow = new UICboxTimKiemWindow(this);
                }
                return this.mUICboxTimKiemWindow;
            }
        }
        
        public UITbTimKiemWindow UITbTimKiemWindow
        {
            get
            {
                if ((this.mUITbTimKiemWindow == null))
                {
                    this.mUITbTimKiemWindow = new UITbTimKiemWindow(this);
                }
                return this.mUITbTimKiemWindow;
            }
        }
        
        public UITìmKiếmWindow UITìmKiếmWindow
        {
            get
            {
                if ((this.mUITìmKiếmWindow == null))
                {
                    this.mUITìmKiếmWindow = new UITìmKiếmWindow(this);
                }
                return this.mUITìmKiếmWindow;
            }
        }
        
        public UIUCSanPhamWindow UIUCSanPhamWindow
        {
            get
            {
                if ((this.mUIUCSanPhamWindow == null))
                {
                    this.mUIUCSanPhamWindow = new UIUCSanPhamWindow(this);
                }
                return this.mUIUCSanPhamWindow;
            }
        }
        
        public UIPnAnhSanPhamWindow UIPnAnhSanPhamWindow
        {
            get
            {
                if ((this.mUIPnAnhSanPhamWindow == null))
                {
                    this.mUIPnAnhSanPhamWindow = new UIPnAnhSanPhamWindow(this);
                }
                return this.mUIPnAnhSanPhamWindow;
            }
        }
        
        public UIPnSanPhamsWindow UIPnSanPhamsWindow
        {
            get
            {
                if ((this.mUIPnSanPhamsWindow == null))
                {
                    this.mUIPnSanPhamsWindow = new UIPnSanPhamsWindow(this);
                }
                return this.mUIPnSanPhamsWindow;
            }
        }
        
        public UITrên5TriệuWindow UITrên5TriệuWindow
        {
            get
            {
                if ((this.mUITrên5TriệuWindow == null))
                {
                    this.mUITrên5TriệuWindow = new UITrên5TriệuWindow(this);
                }
                return this.mUITrên5TriệuWindow;
            }
        }
        
        public UIDưới5TriệuTrên2TriệuWindow UIDưới5TriệuTrên2TriệuWindow
        {
            get
            {
                if ((this.mUIDưới5TriệuTrên2TriệuWindow == null))
                {
                    this.mUIDưới5TriệuTrên2TriệuWindow = new UIDưới5TriệuTrên2TriệuWindow(this);
                }
                return this.mUIDưới5TriệuTrên2TriệuWindow;
            }
        }
        
        public UIDưới2TriệuWindow UIDưới2TriệuWindow
        {
            get
            {
                if ((this.mUIDưới2TriệuWindow == null))
                {
                    this.mUIDưới2TriệuWindow = new UIDưới2TriệuWindow(this);
                }
                return this.mUIDưới2TriệuWindow;
            }
        }
        
        public UIGiáTiềnWindow UIGiáTiềnWindow
        {
            get
            {
                if ((this.mUIGiáTiềnWindow == null))
                {
                    this.mUIGiáTiềnWindow = new UIGiáTiềnWindow(this);
                }
                return this.mUIGiáTiềnWindow;
            }
        }
        
        public UIItem24000000Window UIItem24000000Window
        {
            get
            {
                if ((this.mUIItem24000000Window == null))
                {
                    this.mUIItem24000000Window = new UIItem24000000Window(this);
                }
                return this.mUIItem24000000Window;
            }
        }
        
        public UIItem1CáiWindow UIItem1CáiWindow
        {
            get
            {
                if ((this.mUIItem1CáiWindow == null))
                {
                    this.mUIItem1CáiWindow = new UIItem1CáiWindow(this);
                }
                return this.mUIItem1CáiWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICboxTimKiemWindow mUICboxTimKiemWindow;
        
        private UITbTimKiemWindow mUITbTimKiemWindow;
        
        private UITìmKiếmWindow mUITìmKiếmWindow;
        
        private UIUCSanPhamWindow mUIUCSanPhamWindow;
        
        private UIPnAnhSanPhamWindow mUIPnAnhSanPhamWindow;
        
        private UIPnSanPhamsWindow mUIPnSanPhamsWindow;
        
        private UITrên5TriệuWindow mUITrên5TriệuWindow;
        
        private UIDưới5TriệuTrên2TriệuWindow mUIDưới5TriệuTrên2TriệuWindow;
        
        private UIDưới2TriệuWindow mUIDưới2TriệuWindow;
        
        private UIGiáTiềnWindow mUIGiáTiềnWindow;
        
        private UIItem24000000Window mUIItem24000000Window;
        
        private UIItem1CáiWindow mUIItem1CáiWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICboxTimKiemWindow : WinWindow
    {
        
        public UICboxTimKiemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboxTimKiem";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICboxTimKiemComboBox
        {
            get
            {
                if ((this.mUICboxTimKiemComboBox == null))
                {
                    this.mUICboxTimKiemComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICboxTimKiemComboBox.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUICboxTimKiemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICboxTimKiemComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITbTimKiemWindow : WinWindow
    {
        
        public UITbTimKiemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "tbTimKiem";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinEdit UITbTimKiemEdit
        {
            get
            {
                if ((this.mUITbTimKiemEdit == null))
                {
                    this.mUITbTimKiemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITbTimKiemEdit.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUITbTimKiemEdit;
            }
        }
        
        public WinEdit UITbTimKiemEdit1
        {
            get
            {
                if ((this.mUITbTimKiemEdit1 == null))
                {
                    this.mUITbTimKiemEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUITbTimKiemEdit1.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUITbTimKiemEdit1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITbTimKiemEdit;
        
        private WinEdit mUITbTimKiemEdit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITìmKiếmWindow : WinWindow
    {
        
        public UITìmKiếmWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnTimKiem";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinButton UITìmKiếmButton
        {
            get
            {
                if ((this.mUITìmKiếmButton == null))
                {
                    this.mUITìmKiếmButton = new WinButton(this);
                    #region Search Criteria
                    this.mUITìmKiếmButton.SearchProperties[WinButton.PropertyNames.Name] = "Tìm Kiếm";
                    this.mUITìmKiếmButton.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUITìmKiếmButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUITìmKiếmButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIUCSanPhamWindow : WinWindow
    {
        
        public UIUCSanPhamWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "UCSanPham";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinClient UIUCSanPhamClient
        {
            get
            {
                if ((this.mUIUCSanPhamClient == null))
                {
                    this.mUIUCSanPhamClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIUCSanPhamClient.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUIUCSanPhamClient;
            }
        }
        
        public WinText UIItemText
        {
            get
            {
                if ((this.mUIItemText == null))
                {
                    this.mUIItemText = new WinText(this);
                    #region Search Criteria
                    this.mUIItemText.SearchProperties[WinText.PropertyNames.Name] = "+";
                    this.mUIItemText.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUIItemText;
            }
        }
        
        public WinText UIItemText1
        {
            get
            {
                if ((this.mUIItemText1 == null))
                {
                    this.mUIItemText1 = new WinText(this);
                    #region Search Criteria
                    this.mUIItemText1.SearchProperties[WinText.PropertyNames.Name] = "-";
                    this.mUIItemText1.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUIItemText1;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIUCSanPhamClient;
        
        private WinText mUIItemText;
        
        private WinText mUIItemText1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIPnAnhSanPhamWindow : WinWindow
    {
        
        public UIPnAnhSanPhamWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "pnAnhSanPham";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinClient UIPnAnhSanPhamClient
        {
            get
            {
                if ((this.mUIPnAnhSanPhamClient == null))
                {
                    this.mUIPnAnhSanPhamClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIPnAnhSanPhamClient.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUIPnAnhSanPhamClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIPnAnhSanPhamClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIPnSanPhamsWindow : WinWindow
    {
        
        public UIPnSanPhamsWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "pnSanPhams";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinClient UIPnSanPhamsClient
        {
            get
            {
                if ((this.mUIPnSanPhamsClient == null))
                {
                    this.mUIPnSanPhamsClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIPnSanPhamsClient.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUIPnSanPhamsClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIPnSanPhamsClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITrên5TriệuWindow : WinWindow
    {
        
        public UITrên5TriệuWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "rdoTren5Trieu";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UITrên5TriệuRadioButton
        {
            get
            {
                if ((this.mUITrên5TriệuRadioButton == null))
                {
                    this.mUITrên5TriệuRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUITrên5TriệuRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Trên 5 Triệu";
                    this.mUITrên5TriệuRadioButton.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUITrên5TriệuRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUITrên5TriệuRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIDưới5TriệuTrên2TriệuWindow : WinWindow
    {
        
        public UIDưới5TriệuTrên2TriệuWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "rdoDuoi5Trieu";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIDưới5TriệuTrên2TriệuRadioButton
        {
            get
            {
                if ((this.mUIDưới5TriệuTrên2TriệuRadioButton == null))
                {
                    this.mUIDưới5TriệuTrên2TriệuRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUIDưới5TriệuTrên2TriệuRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Dưới 5 Triệu Trên 2 Triệu";
                    this.mUIDưới5TriệuTrên2TriệuRadioButton.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUIDưới5TriệuTrên2TriệuRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIDưới5TriệuTrên2TriệuRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIDưới2TriệuWindow : WinWindow
    {
        
        public UIDưới2TriệuWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "rdoDuoi2Trieu";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIDưới2TriệuRadioButton
        {
            get
            {
                if ((this.mUIDưới2TriệuRadioButton == null))
                {
                    this.mUIDưới2TriệuRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUIDưới2TriệuRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Dưới 2 Triệu";
                    this.mUIDưới2TriệuRadioButton.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUIDưới2TriệuRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIDưới2TriệuRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGiáTiềnWindow : WinWindow
    {
        
        public UIGiáTiềnWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cbCongThemGiaTien";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIGiáTiềnCheckBox
        {
            get
            {
                if ((this.mUIGiáTiềnCheckBox == null))
                {
                    this.mUIGiáTiềnCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIGiáTiềnCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "+ Giá Tiền";
                    this.mUIGiáTiềnCheckBox.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUIGiáTiềnCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIGiáTiềnCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItem24000000Window : WinWindow
    {
        
        public UIItem24000000Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTongTien";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTongTienEdit
        {
            get
            {
                if ((this.mUITxtTongTienEdit == null))
                {
                    this.mUITxtTongTienEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTongTienEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Tổng Số Lượng: ";
                    this.mUITxtTongTienEdit.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUITxtTongTienEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTongTienEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItem1CáiWindow : WinWindow
    {
        
        public UIItem1CáiWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTongSoLuong";
            this.WindowTitles.Add("frmQuanLy");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTongSoLuongEdit
        {
            get
            {
                if ((this.mUITxtTongSoLuongEdit == null))
                {
                    this.mUITxtTongSoLuongEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTongSoLuongEdit.WindowTitles.Add("frmQuanLy");
                    #endregion
                }
                return this.mUITxtTongSoLuongEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTongSoLuongEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFrmChonKhachHangWindow : WinWindow
    {
        
        public UIFrmChonKhachHangWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "frmChonKhachHang";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("frmChonKhachHang");
            #endregion
        }
        
        #region Properties
        public UIXácNhậnWindow UIXácNhậnWindow
        {
            get
            {
                if ((this.mUIXácNhậnWindow == null))
                {
                    this.mUIXácNhậnWindow = new UIXácNhậnWindow(this);
                }
                return this.mUIXácNhậnWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIXácNhậnWindow mUIXácNhậnWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIXácNhậnWindow : WinWindow
    {
        
        public UIXácNhậnWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnXacNhan";
            this.WindowTitles.Add("frmChonKhachHang");
            #endregion
        }
        
        #region Properties
        public WinButton UIXácNhậnButton
        {
            get
            {
                if ((this.mUIXácNhậnButton == null))
                {
                    this.mUIXácNhậnButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIXácNhậnButton.SearchProperties[WinButton.PropertyNames.Name] = "Xác Nhận";
                    this.mUIXácNhậnButton.WindowTitles.Add("frmChonKhachHang");
                    #endregion
                }
                return this.mUIXácNhậnButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIXácNhậnButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIThôngBáoWindow : WinWindow
    {
        
        public UIThôngBáoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thông Báo";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Thông Báo");
            #endregion
        }
        
        #region Properties
        public WinControl UIThôngBáoDialog
        {
            get
            {
                if ((this.mUIThôngBáoDialog == null))
                {
                    this.mUIThôngBáoDialog = new WinControl(this);
                    #region Search Criteria
                    this.mUIThôngBáoDialog.SearchProperties[UITestControl.PropertyNames.Name] = "Thông Báo";
                    this.mUIThôngBáoDialog.SearchProperties[UITestControl.PropertyNames.ControlType] = "Dialog";
                    this.mUIThôngBáoDialog.WindowTitles.Add("Thông Báo");
                    #endregion
                }
                return this.mUIThôngBáoDialog;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIThôngBáoDialog;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Thông Báo");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Thông Báo");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
